# ingress-nginx-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-app.yaml
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after cert-manager
spec:
  project: default
  source:
    repoURL: https://github.com/chadmcrowell/my-gitops-repo.git
    targetRevision: main
    path: infrastructure/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
